# Generated by Django 3.0.2 on 2020-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userAdderss',
            new_name='userUniversity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userAccount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPhone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userRank',
        ),
        migrations.AddField(
            model_name='user',
            name='userEmail',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userFace',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
