# Generated by Django 3.0.2 on 2020-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200108_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.CharField(max_length=31),
        ),
    ]
