# Generated by Django 3.0.2 on 2020-01-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20200108_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=31)),
                ('orderId', models.CharField(max_length=20)),
                ('publish_text', models.CharField(max_length=2000)),
                ('userImg', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('publish_type', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
