# Generated by Django 3.0.2 on 2020-01-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_courseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
