# Generated by Django 3.0.2 on 2020-01-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_courseinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
