# Generated by Django 3.0.2 on 2020-01-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_courseinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userForm', models.CharField(max_length=31)),
                ('userTo', models.CharField(max_length=31)),
                ('shopId', models.CharField(max_length=20)),
                ('usersInfo', models.CharField(max_length=2000)),
                ('userRemind', models.IntegerField()),
            ],
        ),
    ]
