# Generated by Django 3.0.2 on 2020-01-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20200117_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='shopId',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='userTo',
            field=models.CharField(max_length=31, primary_key=True, serialize=False),
        ),
    ]
