# Generated by Django 3.0.2 on 2020-01-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_usergroup_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='toImg',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='toName',
            field=models.CharField(default=1, max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='toShopimg',
            field=models.CharField(default=1, max_length=51),
            preserve_default=False,
        ),
    ]
