# Generated by Django 3.0.2 on 2020-01-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20200117_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='toImg',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='toShopimg',
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='orderId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
