# Generated by Django 3.0.2 on 2020-01-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_auto_20200117_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='userTo',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('userForm', 'userTo')},
        ),
    ]
