# Generated by Django 3.0.2 on 2020-01-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20200117_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='userEmail',
            new_name='userphone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userEmail',
            new_name='userphone',
        ),
    ]
