# Generated by Django 3.0.2 on 2020-01-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_auto_20200117_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='buyer',
            field=models.BooleanField(default=True),
        ),
    ]
