# Generated by Django 3.0.2 on 2020-03-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
