# Generated by Django 3.0.2 on 2020-03-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20200327_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('shopid', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('sellid', models.CharField(max_length=20)),
            ],
        ),
    ]
