# Generated by Django 3.0.2 on 2020-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiedTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('userIdCard', models.CharField(max_length=40)),
                ('postgraduateQualified', models.CharField(max_length=40)),
                ('isexperience', models.BooleanField(default=False)),
                ('canCourse', models.CharField(max_length=100)),
                ('majorQualified', models.CharField(max_length=50)),
            ],
        ),
    ]
