# Generated by Django 3.0.2 on 2020-03-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_auto_20200328_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=400)),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DaKa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('userId', models.CharField(max_length=20)),
                ('sellid', models.CharField(max_length=20)),
                ('courseid', models.CharField(max_length=20)),
                ('userdaka', models.CharField(max_length=10)),
                ('selldaka', models.CharField(max_length=10)),
                ('backinfo', models.CharField(max_length=100)),
            ],
        ),
    ]
